steps:
  - id: 'Populate Maven cache from bucket'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/snpcheck/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - id: 'Build application'
    name: 'europe-west4-docker.pkg.dev/hmf-build/hmf-docker/maven:3.6.0-jdk-11-slim-libarray-diff-perl'
    entrypoint: 'mvn'
    args:
      - 'install'
      - '--batch-mode'
      - '--activate-profiles'
      - 'release'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  - id: 'Save Maven cache'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/snpcheck/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - id: 'Publish docker image'
    name: 'europe-west4-docker.pkg.dev/hmf-build/hmf-docker/docker-tag'
    args: ['europe-west4-docker.pkg.dev/hmf-build/hmf-docker/snpcheck', '$TAG_NAME']
options:
  machineType: 'E2_HIGHCPU_8'
images:
  - europe-west4-docker.pkg.dev/hmf-build/hmf-docker/snpcheck
