steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/snpcheck/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - name: 'eu.gcr.io/hmf-build/maven:3.6.0-jdk-11-slim-libarray-diff-perl'
    entrypoint: 'mvn'
    args:
      - 'install'
      - '--batch-mode'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/snpcheck/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Building image'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/snpcheck:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    entrypoint: '/bin/bash'
    args: ['-c', "docker push eu.gcr.io/$PROJECT_ID/snpcheck:$SHORT_SHA"]
options:
  machineType: 'N1_HIGHCPU_32'
images:
  - eu.gcr.io/$PROJECT_ID/snpcheck
